### ISSUE TITLE
뉴스 불러올 때, id 번호가 순서가 뒤죽박죽일 때가 있음.

### ISSUE THREAD

**Issue by ynifamily3** [ynifamily3/korean_fake_news_detector#47]
네이버 문제일 가능성이 높지만, 뒤죽박죽인 경우 offset계산에 애를 먹게 됨 (중복된 뉴스가 나오는 등)

![image](https://user-images.githubusercontent.com/13795765/83974036-3f5a7b80-a925-11ea-9180-0bfc8fe00036.png)

그림에서, 133911 다음에 갑자기 133897이 나옴

**Comment by vbalien** [comment]
쿼리를 보여주세요.

**Comment by vbalien** [comment]
id로 먼저 정렬을 시켜주는게 좋겠네요. 수정하겠습니다.
